### ISSUE TITLE
Backend claims v6.3 in footer.

### ISSUE THREAD

**Issue by rhullah** [Sitefinity-SDK/Telerik.Sitefinity.Samples.Corporate#2]
While looking at the backend of the site, the footer claims version is 6.3 while all the assemblies/NuGet packages say 7.2.*

![footer](https://cloud.githubusercontent.com/assets/2235616/5455072/3ea1ff22-8506-11e4-8365-6686b295bae3.PNG)

**Comment by grumpycatsaysno** [comment]
Thank you for the feedback. 

It seems that the label did not update properly during the upgrade process. In order to suit it to your current version of the project, you can navigate to Administration -> Interface & Labels and search for: Sitefinity 6.3. Change the value to your version and save changes. The label will be updated properly.
